name: flutter_sinhala
description: Sinhala Fonts for Flutter
repository: https://github.com/iamchathu/flutter-sinhala

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

