name: flutter_sinhala
description: Collection of Sinhala Fonts to be used with Flutter development.
repository: https://github.com/iamchathu/flutter-sinhala.git

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

